app/ontocreate/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField


class OntologyDescript(FlaskForm):
    """Form used to save modification of nodes in the onotlogy create tool"""

    onto_id_ext = StringField(
        "ID Ontologie Externe",
        render_kw={
            "placeholder": "ID Ontologie Externe",
            "class": "form-control",
            "readonly": "",
        },
    )
    onto_name = StringField(
        "Nom Terme Ontologique",
        render_kw={
            "placeholder": "Nom Terme Ontologique",
            "class": "form-control",
            "readonly": "",
        },
    )
    parent_id = StringField(
        "ID Parent",
        render_kw={"placeholder": "ID Parent", "class": "form-control", "readonly": ""},
    )

    synonymes = StringField(
        "Synonymes", render_kw={"placeholder": "Synonymes", "class": "form-control"}
    )
    gene = StringField(
        "Gene associé",
        render_kw={"placeholder": "Gene associé", "class": "form-control"},
    )
    description = TextAreaField(
        "Description",
        render_kw={
            "placeholder": "Description",
            "class": "form-control",
            "cols": "3",
            "rows": "5",
        },
    )

app/ontocreate/__init__.py
from flask import Blueprint

bp = Blueprint(
    "ontocreate",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/static/ontocreate",
)

from app.ontocreate import routes

app/ontocreate/routes.py
import os
import json
from flask import render_template, current_app, send_from_directory, request
from flask_login import login_required
from app import db
from app.ontocreate import bp
from app.ontocreate.forms import OntologyDescript
from app.models import ReportHisto
from app.historeport.onto_func import Ontology


@bp.route("/config/<path:filename>")
@login_required
def onto_json(filename):
    """Serve files located in patient subfolder inside folder"""
    return send_from_directory(current_app.config["CONFIG_FOLDER"], filename)


@bp.route("/ontocreate", methods=["GET", "POST"])
@login_required
def ontocreate():
    """View used to show and modify ontology tree"""
    form = OntologyDescript()
    return render_template("ontocreate.html", form=form)


@bp.route("/modify_onto", methods=["PATCH"])
@login_required
def modify_onto():
    """Update ontology json file with PATCH Ajax Request from JSTree"""
    # Get AJAX JSON data and parse it
    raw_data = request.get_data()
    parsed = json.loads(raw_data)
    dirty_tree = {
        i["id"]: {
            "id": i["id"],
            "text": i["text"],
            "icon": i["icon"],
            "data": i["data"],
            "parent": i["parent"],
        }
        for i in parsed
    }
    clean_tree = []
    for i in dirty_tree:
        clean_tree.append(dirty_tree[i])
    with open(
        os.path.join(current_app.config["CONFIG_FOLDER"], "ontology.json"), "w"
    ) as json_file:
        json.dump(clean_tree, json_file, indent=4)

    # Update All Reports to the latest Version of ontology
    reports = ReportHisto.query.all()
    template_ontology = Ontology(clean_tree)
    for i in reports:
        current_report_ontology = Ontology(i.ontology_tree)
        updated_report_ontology = current_report_ontology.update_ontology(
            template_ontology
        )
        i.ontology_tree = updated_report_ontology
    db.session.commit()
    return json.dumps({"success": True}), 200, {"ContentType": "application/json"}

app/ontocreate/templates/ontocreate.html
{% extends "base.html"%}
{% block content %}
<!-- JS Tree -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.11/themes/default/style.min.css"
    integrity="sha512-P8BwDSUInKMA7I116Z1RFg/Dfk85uFdliEUYO7vQlwtxLVMNvZimfMAQsaf++9EhlAGOVX6yhDQAIY3/70jDUg=="
    crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.11/jstree.min.js"
    integrity="sha512-bU6dl4fd2XN3Do3aWypPP2DcKywDyR3YlyszV+rOw9OpglrGyBs6TyTsbglf9umgE+sy+dKm1UHhi07Lv+Vtfg=="
    crossorigin="anonymous"></script>

<!-- Tagify -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tagify/3.23.1/tagify.css"
    integrity="sha512-1CG2eaZ3B/p7OqthY2eBpVCD2A+0b2T7aEXfMnr4FqZFoKddxURdxcD8EcKI66qthtkGAWA/Hnwy7ceNHcHJKw=="
    crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/tagify/3.23.1/tagify.min.js"
    integrity="sha512-jb/SYEPmc1tGaJ3Yu6CZaOBhn8sqTpgTqVcXUm4udHGaUsBIOj6DsIc6aXZpsvXhtexnmIowmOVBHKuIwyB2Rw=="
    crossorigin="anonymous"></script>

<div class="row">
    <div class="col-xl">
        <h1>Arbre Ontologie</h1>

        <input type="text" id="plugins4_q" value="" type="search" id="form1" class="form-control"
            placeholder="Rechercher">
        <div id="jstree" class="demo" style="overflow:scroll; max-height: 600px;"></div>

        <button type="button" class="btn btn-success" onclick="save_tree()">Sauvegarder Arbre</button>
    </div>
    <div class="col-xl">
        <h1>Info Terme</h1>
        <form method="post">
            <div class="form-group">
                {% for error in form.errors %}
                <span style="color: red;">{{ error }}: {{form.errors[error]}}</span>
                {% endfor %}
                {{ form.hidden_tag() }}
                {{ form.onto_id_ext }}
                {{ form.onto_name }}
                {{ form.parent_id }}
                {{ form.synonymes }}
                {{ form.gene }}
                {{ form.description }}
                <button type="button" class="btn btn-success" onclick="update_node_data()">Update</button>
            </div>
        </form>
    </div>
</div>
<meta id="data-url" data-jstree="{{url_for('ontocreate.onto_json', filename='ontology.json')}}" data-savetree="{{url_for('ontocreate.modify_onto')}}">
<script src="{{ url_for('ontocreate.static', filename='ontocreate.js') }}"></script>
{% endblock %}