app/ocr/forms.py
import os
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, SubmitField, SelectField, TextAreaField
from wtforms.validators import ValidationError, DataRequired
import app.src.common as Common


class PdfForm(FlaskForm):
    """Form used for handling of PDF upload associated to patient"""

    pdf = FileField(
        validators=[
            FileRequired(),
            FileAllowed(["pdf"], "This file is not a valid PDF File !"),
        ],
        render_kw={"class": "form-control-file border"},
    )
    patient_ID = StringField(
        "patient_ID",
        validators=[DataRequired()],
        render_kw={"placeholder": "Patient ID", "class": "form-control"},
    )

    lang = SelectField(
        "lang",
        validators=[DataRequired()],
        choices=Common.create_lang_list(os.path.join("config", "config_lang_ocr.tsv")),
        render_kw={"placeholder": "PDF Langage", "class": "form-control custom-select"},
    )
    submit = SubmitField("Upload", render_kw={"class": "btn btn-primary mb-2"})


class DeleteButton(FlaskForm):
    """Empty form for delete button"""

    submit = SubmitField("Confirm Deletion", render_kw={"class": "btn btn-danger"})

app/ocr/__init__.py
from flask import Blueprint

bp = Blueprint("ocr", __name__, template_folder="templates")

from app.ocr import routes

app/ocr/routes.py
import os

from flask import flash, request, redirect, url_for
from flask import render_template, send_from_directory, current_app
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename

from app import db
from app.ocr import bp
from app.ocr.forms import PdfForm, DeleteButton
from app.models import Pdf
from app.ocr.ocr import Rapport


@bp.route("/data/<path:filename>")
@login_required
def data_folder(filename):
    """Serve files located in patient subfolder inside folder"""
    return send_from_directory(current_app.config["DATA_FOLDER"], filename)


@bp.route("/upload_pdf", methods=["GET", "POST"])
@login_required
def upload_pdf():
    """Page to upload a new PDF file."""
    form = PdfForm()
    delete_button = DeleteButton()
    pdf_history = Pdf.query.all()

    # if valid file uploaded: save it and create db entry
    if form.validate_on_submit():
        file = form.pdf.data
        filename = secure_filename(form.patient_ID.data + "_" + file.filename)

        # Create a data folder for patient
        data_patient_dir = os.path.join(
            current_app.config["DATA_FOLDER"], form.patient_ID.data
        )
        if not os.path.exists(data_patient_dir):
            os.makedirs(data_patient_dir)

        # Save the PDF to patient data folder
        file.save(os.path.join(data_patient_dir, filename))

        # Create our new PDF & Patient database entry
        pdf = Pdf(
            pdf_name=filename,
            patient_id=form.patient_ID.data,
            expert_id=current_user.id,
            lang=form.lang.data,
            pdf_path=os.path.join(data_patient_dir, filename),
        )

        # Check if the PDF or patient already exist in DB (same filename & patient ID)
        # If not: add it to DB

        if not pdf.isduplicated():
            db.session.add(pdf)

        db.session.commit()

        # Finally redirect to annotation
        return redirect(url_for("ocr.ocr_results", id=pdf.id))
    return render_template(
        "ocr_upload.html",
        form=form,
        pdf_history=pdf_history,
        delete_button=delete_button,
    )


@bp.route("/ocr_results", methods=["GET", "POST"])
@login_required
def ocr_results():
    """Perform OCR on PDF and render form to edit OCR results."""
    # Query the database from arg in get request
    pdf_requested = Pdf.query.get(request.args.get("id"))

    # If PDF exist in database: serve it
    if pdf_requested is not None:
        pdf_object = Rapport(path=pdf_requested.pdf_path, lang=pdf_requested.lang)
        rel_filepath = os.path.join(
            "data", pdf_requested.patient_id, pdf_requested.pdf_name
        )

        pdf_object.pdf_to_text()
        pdf_object.detect_sections()
        pdf_object.extract_section_text()
        section_test_dict = pdf_object.section_text

    # Error handling
    elif pdf_requested is None:
        flash("PDF doesn't exist!", "error")
        return redirect(url_for("ocr.upload_pdf"))

    # Base Page
    return render_template(
        "ocr_results.html",
        patient_id=request.args.get("patient_id"),
        rel_filepath=rel_filepath,
        section_test_dict=section_test_dict,
    )


@bp.route("/delete_pdf/<id_pdf>", methods=["POST"])
@login_required
def delete_pdf(id_pdf):
    """Page delete a histology report from database with delete button."""
    form = DeleteButton()
    # Retrieve database entry and delete it if existing
    if form.validate_on_submit():
        pdf = Pdf.query.get(id_pdf)
        if pdf is None:
            flash("PDF {} not found.".format(id_pdf), "danger")
            return redirect(url_for("ocr.upload_pdf"))
        db.session.delete(pdf)
        db.session.commit()
        flash("Deleted PDF entry {}!".format(id_pdf), "success")
        return redirect(url_for("ocr.upload_pdf"))
    else:
        return redirect(url_for("ocr.upload_pdf"))

app/ocr/templates/ocr_results.html
{% extends "base.html"%}
{% block content %}
<div class="row">
    <div class="col-xl">
        <h1>PDF Viewer</h1>
        <embed src="{{rel_filepath}}" width="100%" height="700px" />
    </div>

    <div class="col-xl">
        <h1>OCR</h1>
        <div class="accordion" id="accordionOCR">
            {% for key,value in section_test_dict.items() %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{loop.index}}">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapse{{loop.index}}" aria-expanded="true"
                        aria-controls="collapse{{loop.index}}">
                        {{key}}
                    </button>
                </h2>
                <div id="collapse{{loop.index}}" class="accordion-collapse collapse"
                    aria-labelledby="heading{{loop.index}}" data-bs-parent="#accordionOCR">
                    <div class="accordion-body">{{value}}</div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>

{% endblock %}

app/ocr/templates/ocr_upload.html
{% extends "base.html"%}
{% block content %}
<div class="row">
    <div class="col-xl-3"></div>
    <div class="col-xl-6">
        <h1>Upload New PDF</h1></br>
        <form method=post enctype=multipart/form-data>
            {{ form.hidden_tag() }}
            {% for error in form.errors %}
            <span style="color: red;">{{ error }}: {{form.errors[error]}}</span>
            </br>
            {% endfor %}
            {{ form.patient_ID }}
            <h4>Select a pdf file</h4>
            {{ form.pdf }}
            <h4>Document Langugage</h4>
            {{form.lang}}
            {{ form.submit }}
        </form>
    </div>
    <div class="col-xl-3"></div>
</div>

<div class="row">
    <div class="col-xl">
        <h1>PDF History</h1>
        <table class="table table-striped table-bordered table-hover table-responsive">
            <thead class="table-info">
                <th class="align-middle text-center">PDF ID</th>
                <th class="align-middle text-center">PDF</th>
                <th class="align-middle text-center">Patient ID</th>
                <th class="align-middle text-center">Action</th>
            </thead>
            {% for pdf in pdf_history %}
            <tr>
                <td class="align-middle text-center">{{ pdf.id }}</td>
                <td class="align-middle text-center">{{ pdf.pdf_name }}</td>
                <td class="align-middle text-center">{{ pdf.patient_id }}</td>
                <td class="align-middle text-center"><a class="btn btn-success btn-sm" role="button"
                        href="ocr_results?id={{pdf.id}}">Resume</a>
                    <!-- Button Show Popup -->
                    <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal"
                        data-bs-target="#DeletionPopup">
                        Delete
                    </button>

                    <!-- Deletion Popup -->
                    <div class="modal fade" id="DeletionPopup" tabindex="-1" aria-labelledby="DeletionPopupLabel"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="DeletionPopupLabel">
                                        Confirm Delete Popup
                                    </h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-footer">
                                    <form action="{{ url_for('ocr.delete_pdf', id_pdf=pdf.id) }}" method="post"
                                        style="display: inline;">
                                        {{ delete_button.hidden_tag() }}
                                        {{ delete_button.submit }}
                                    </form>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                        Close
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}